apiVersion: v1
kind: Star
tables:
- name: City
  metadata:
    root: true
  definition:
    type: graphql
    url: 'https://evening-scrubland-62386.herokuapp.com/'
    query: 'city'
  links:
  - to: 'CityEstate'
    as: 'cityEstate'
    sameAt:
      code: cityCode
    type: unique
  # - to: 'CityEstate'
  #   as: 'cityEstate2'
  #   sameAt:
  #     code: cityCode
  #   type: unique
  - to: Location
    as: citySummary
    sameAt:
      cityKanji: Japanese
    # type: single
    type: unique
- name: CityEstate
  definition:
    type: graphql
    url: 'https://frozen-chamber-61303.herokuapp.com/'
    query: 'cityEstate'
- name: Location
  definition:
    type: graphql
    url: 'https://guarded-sierra-71026.herokuapp.com/'
    query: 'location'
  overlays:
  - overlayName: batch
    definition:
      query: 'locations'
